version: "3.8"

services:
  auth:
    build: ./auth
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - AUTH_PORT=${AUTH_PORT}
    networks:
      - go_microservices

  broker:
    build: ./broker
    ports:
      - "${BROKER_PORT}:${BROKER_PORT}"
    environment:
      - BROKER_PORT=${BROKER_PORT}
    networks:
      - go_microservices
  
  logger:
    build: ./logger
    ports: 
      - "${LOGGER_PORT}:${LOGGER_PORT}"
    environment:
      - LOGGER_PORT=${LOGGER_PORT}
      - MONGO_URL=${MONGO_URL}
    networks:
      - go_microservices

  mail:
    build: ./mailer
    ports:
      - "${MAILER_PORT}:${MAILER_PORT}"
    environment:
      - MAILER_PORT=${MAILER_PORT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - FROM_ADDRESS=${FROM_ADDRESS}
      - FROM_NAME=${FROM_NAME}

networks:
  go_microservices:
    driver: bridge
